spring:
  application:
    name: VMeKnowledge2-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  web:
    resources:
      # 需要指定服务器中的具体文件路径
      static-locations: file:/path/to/your/uploads/
  data:
    mongodb:
      host: 182.92.121.103
      port: 3100
      database: Vmeknowledge
    redis:
      host: localhost
      port: 6379
      password: 123456 # 如果没有密码则删除此行
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
server:
  port: 8080
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
