spring:
  application:
    name: VMeKnowledge2-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:/resources/files
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: Vmeknowledge
server:
  port: 8080
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
