spring:
  application:
    name: VMeKnowledge2-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  web:
    resources:
      #需要指定服务器中的具体文件路径
      static-locations: file:/db/test1/mysql
server:
  port: 8080
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
